version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - path: ./backend/.env
        required: true 
  nginx:
    depends_on:
      - backend
      - frontend
      - chatbot
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
  frontend:
    build: 
      context: ./amand_pune
      dockerfile: Dockerfile.dev
  chatbot:
    build: 
      context: ./chatbot
      dockerfile: Dockerfile.dev