version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    command: ["node", "server.js"]
  
  frontend:
    build: 
      context: ./amand_pune
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      HOST: "0.0.0.0"
